# Site settings
title: Shamak Dutta
email: shamakd5@gmail.com
description: > 
baseurl: ""
url: "https://shamak.github.io/"
twitter_username: shamakd5
github_username:  shamak
linkedin_username: https://www.linkedin.com/pub/shamak-dutta/73/42b/733

# Build settings
markdown: kramdown
